/**
 * My Space API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TodoCategory } from './todoCategory';
import { TodoStatus } from './todoStatus';


export interface Todo { 
    todoID?: number;
    caption?: string;
    status?: TodoStatus;
    active?: boolean;
    createdDate?: Date;
    createdBy?: string;
    updatedDate?: Date;
    updatedBy?: string;
    finishDate?: Date;
    finishBy?: string;
    category?: TodoCategory;
}
